final Map<String, bool> muscleGroups = {
  'Traps': false,
  'Shoulders': false,
  'Chest': false,
  'Biceps': false,
  'Triceps': false,
  'Forearm': false,
  'Back': false,
  'Legs': false,
  'Glutes': false,
  'ABS': false,
  'A3BS': false,
  'ABS3': false,
  'AB3S': false,
  'AB33S': false,
  'AB23S': false,
};
